services:
  orion:
    image: telefonicaiot/fiware-orion
    container_name: orion-context-broker
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo
    networks:
      - testnet

  mongo:
    image: mongo:8.0
    container_name: orion-mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - testnet

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "8883:8883"
    volumes:
      - ./mqtt_config:/mosquitto/config
      - ./mqtt_config/passwd:/mosquitto/config/passwd
      - ./mqtt_config/acl:/mosquitto/config/acl
      - /opt/mosquitto-certs/fullchain.pem:/mosquitto/certs/fullchain.pem:ro
      - /opt/mosquitto-certs/privkey.pem:/mosquitto/certs/privkey.pem:ro
    restart: unless-stopped
    networks:
      - testnet  

  data-broker:
    image: alk3rg/techlab-databroker:latest
    container_name: data-broker
    ports:
      - "8000:8000"
    volumes:
      - ./schemas:/app/schemas
    depends_on:
      - mqtt-broker
      - orion
    restart: unless-stopped
    networks:
      - testnet

  mqtt-broker-processor:
    image: alk3rg/techlab-mqttbroker:latest
    container_name: mqtt-broker-processor
    volumes:
      - ./schemas:/app/schemas
    depends_on:
      - mqtt-broker
      - data-broker
    restart: unless-stopped
    networks:
      - testnet
  
  mock-notify-receiver:
    image: alk3rg/techlab-mocknotify:latest
    container_name: mock-notify-receiver
    ports:
      - "9000:9000"
    depends_on:
      - orion
    restart: unless-stopped
    networks:
      - testnet
      
  frontend:
    image: alk3rg/techlab-controlpanel:latest
    container_name: frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SESSION_SECRET=secret
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=techlab
      - DB_PASSWORD=techlabpw
      - DB_NAME=techlab
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - testnet

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=techlab
      - POSTGRES_USER=techlab
      - POSTGRES_PASSWORD=techlabpw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - testnet

volumes:
  mongo_data:
  pg_data:

networks:
  testnet:
    external: true
