services:
  orion:
      image: telefonicaiot/fiware-orion
      container_name: orion-context-broker
      ports:
        - "1026:1026"
      depends_on:
        - mongo
      command: -dbURI mongodb://mongo
      networks:
      - testnet
  
  mongo:
    image: mongo:8.0
    container_name: orion-mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - testnet

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    command: >
      sh -c "echo 'listener 1883' > /mosquitto/config/mosquitto.conf &&
             echo 'allow_anonymous true' >> /mosquitto/config/mosquitto.conf &&
             /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
    restart: unless-stopped
    networks:
      - testnet
  
  data-broker:
    build:
      context: ./backend
      dockerfile: Dockerfile.databroker
    container_name: data-broker
    ports:
      - "8000:8000"
    depends_on:
      - mqtt-broker
      - orion
    restart: unless-stopped
    networks:
      - testnet
  
  mqtt-broker-processor:
    tty: true
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile.mqttbroker
    container_name: mqtt-broker-processor
    depends_on:
      - mqtt-broker
      - data-broker
    restart: unless-stopped
    networks:
      - testnet
  
  mock-notify-receiver:
    build:
      context: ./backend
      dockerfile: Dockerfile.mocknotify
    container_name: mock-notify-receiver
    ports:
      - "9000:9000"
    depends_on:
      - orion
    restart: unless-stopped
    networks:
      - testnet

  microfrontend:
    build:
      context: ./microfrontend
      dockerfile: Dockerfile
    container_name: microfrontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - testnet

volumes:
  mongo_data:

networks:
  testnet:
    external: true
