services:
  orion:
    image: telefonicaiot/fiware-orion
    container_name: orion-context-broker
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo
    networks:
      - testnet

  mongo:
    image: mongo:8.0
    container_name: orion-mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - testnet

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt_config:/mosquitto/config
      - /opt/mosquitto-certs/fullchain.pem:/mosquitto/certs/fullchain.pem:ro
      - /opt/mosquitto-certs/privkey.pem:/mosquitto/certs/privkey.pem:ro
    restart: unless-stopped
    networks:
      - testnet  

  data-broker:
    image: alk3rg/techlab-databroker:latest
    container_name: data-broker
    ports:
      - "8000:8000"
    depends_on:
      - mqtt-broker
      - orion
    restart: unless-stopped
    networks:
      - testnet

  mqtt-broker-processor:
    image: alk3rg/techlab-mqttbroker:latest
    container_name: mqtt-broker-processor
    depends_on:
      - mqtt-broker
      - data-broker
    restart: unless-stopped
    networks:
      - testnet
  
  mock-notify-receiver:
    image: alk3rg/techlab-mocknotify:latest
    container_name: mock-notify-receiver
    ports:
      - "9000:9000"
    depends_on:
      - orion
    restart: unless-stopped
    networks:
      - testnet
      
  microfrontend:
    image: alk3rg/techlab-microfrontend:latest
    container_name: microfrontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - testnet

volumes:
  mongo_data:

networks:
  testnet:
    external: true
